# Generated by Django 4.0.1 on 2022-01-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='userID',
            new_name='username',
        ),
    ]
